### ISSUE TITLE
shinyTree in shinydashboard sidebar

### ISSUE THREAD

**Issue by vorpalvorpal** [shinyTree/shinyTree#108]
shinyTree does not seem to work in shinydashboard sidebars. 

Not working code below:

```
library(shiny)
library(shinyTree)
library(shinydashboard)
library(shinydashboardPlus)

header <- dashboardHeader(title = "MWE")
body <- dashboardBody(
  # works fine in the body
  shinyTree("tree", stripes = TRUE, multiple = FALSE, animation = FALSE)
)
sidebar <- dashboardSidebar(
  # doesn't work here
  # shinyTree("tree", stripes = TRUE, multiple = FALSE, animation = FALSE)
  sidebarMenu(
    # doesn't work here
    # shinyTree("tree", stripes = TRUE, multiple = FALSE, animation = FALSE)
    menuItem("test"
         # or here
         # shinyTree("tree", stripes = TRUE, multiple = FALSE, animation = FALSE)
    )
  )
)

shinyUI(
  dashboardPage(
   header = header,
   sidebar = sidebar,
   body = body
  )
)

shinyServer(function(input, output, session) {
  # Simplified test tree
  output$tree <- renderTree({
    list(
      root1 = "",
      root2 = list(
        SubListA = list(leaf1 = "", leaf2 = "", leaf3=""),
        SubListB = list(leafA = "", leafB = "")
      ),
      root3 = list(
        SubListA = list(leaf1 = "", leaf2 = "", leaf3=""),
        SubListB = list(leafA = "", leafB = "")
      )
    )
  })
})
```

I'm not sure if I'm just missing something really obvious, but my searching on google and stackoverflow hasn't brought anything up.

**Comment by bellma-lilly** [comment]
@vorpalvorpal This worked for me in all cases on a mac and linux with R 4.0.5
Can you be more specific when you say "it doesn't work"?

**Comment by vorpalvorpal** [comment]
Well, I'm an idiot. I didn't realise that there could only be a single instance of a shinyTree in the ui. When I ran it with the shinyTree in the sidebar nothing showed up because the shinyTree in the body section was still there. But if I comment out the one in the body the one in the sidebar works fine. 

Sorry for wasting your time.

**Comment by bellma-lilly** [comment]
@vorpalvorpal Certainly not a waste of time. You actually can have more than one instance, but you have to do some bookkeeping. First, give each tree a separate name:
shinyTree("tree", stripes = TRUE, multiple = FALSE, animation = FALSE)
shinyTree("tree2", stripes = TRUE, multiple = FALSE, animation = FALSE)

Then, you have to have separate outputs:
output$tree <- renderTree({...})
output$tree2 <- renderTree({...})
