### ISSUE TITLE
Updating Docs + CRAN 

### ISSUE THREAD

**Issue by KoniWatsonVekta** [shinyTree/shinyTree#119]
Issue #112 has already discussed this but would like to bring it back up.

I am not even able to deploy my shiny application to RConnect because I have installed and using shinyTree v0.3.0 features and on deployment it fails due to:

`[Connect] 2023/03/23 10:43:23.658263352 FAILED
[Connect] 2023/03/23 10:43:23.658514110 Error in getSourceForPkgRecord(pkgRecord, srcDir(project), availablePackagesSource(repos = repos), : Failed to download package from URL:
[Connect] 2023/03/23 10:43:23.658530529 - 'https://api.github.com/repos/shinyTree/shinyTree/tarball/d8db27067d7f244b25f3147204d564c5422bd64c'`

Looking at CRAN and the git for the CRAN download they are both saying shinyTree is on v0.2.7 could an update potentially be made?

**Comment by bellma-lilly** [comment]
Just submitted current release to CRAN
