### ISSUE TITLE
Tree render gone if the panel is being collapsed by opening another panel 

### ISSUE THREAD

**Issue by rdemets** [shinyTree/shinyTree#123]
Hi. I found two issues describing the same problem, but somehow, the solution doesn't seem to work for me. (#79 #87). 

My problem is that I am not planning on clicking on a button to re-render the tree, so I dont really know how to work around it. 

By inspecting the page, I can see that the line `<ul class="jstree-container-ul jstree-children jstree-no-icons jstree-striped" role="group">` gets a new argument `style="display: none;"` once another panel is open, and this will not be overwritten when I reopen the panel. Typing something in the text bar does restore display to block, but I dont know how to force display : block when I click on the panel. I found a workaround when I was using another type of tree, but I cant find how to adapt it to shinytree. 

`js <- "
$(document).ready(function() {
    $('a[href=\"#shiny-tab-location\"').on('click', function() {
        $('.treejs-nodes').css('display', 'block');
    });
})
"`

A small code to replicate the issue. Please let me know if a GIF of the issue would help. 

```
library(shiny)
library(shinyTree)
library(shinyjs)

ui <- dashboardPage(
  dashboardHeader(title = "Filters"),
  dashboardSidebar(
    # Increase the width of the sidebar panel
    useShinyjs(),
    sidebarMenu(
      menuItem("By Location", tabName = "location", icon = icon("earth-europe"),
               div(
                 style = "max-height: 42vh; overflow-y: auto; overflow-x: auto;",  # Set the maximum height and provide a scrollbar
                 shinyTree("tree", stripes = TRUE, multiple = TRUE, animation = TRUE, checkbox = TRUE, search=TRUE, themeIcons = FALSE)
               )
               
      ),
      
      menuItem("By Technique", tabName = "technique", icon = icon("microscope"),
               fluidRow(
                 # Adjust column sizing and spacing
                 column(3, actionBttn(inputId = "group1_btn", label = "Btn1", style = "jelly", color = "danger")),
                 column(3, actionBttn(inputId = "group2_btn", label = "Btn1", style = "jelly", color = "danger")),
                 column(3, actionBttn(inputId = "group3_btn", label = "Btn1", style = "jelly", color = "danger"))
                 
               ),
               
               # Technique checkboxes will be displayed here in the body
               uiOutput("technique_checkboxes")
               
    ))),
  dashboardBody(
    DTOutput("table")
  ))

server <- function(input, output, session) {
  output$tree <- renderTree({
    list(
      root1 = list(
        SubListA = list(leaf1 = "", leaf2 = "", leaf3=""),
        SubListAB = list(leaf1 = "", leaf2 = "", leaf3=""),
        SubListAC = list(leaf1 = "", leaf2 = "", leaf3="")
      ),
      root2 = list(
        SubListB = list(leaf1 = "", leaf2 = "", leaf3=""),
        SubListBA = list(leaf1 = "", leaf2 = "", leaf3=""),
        SubListBC = list(leafA = "", leafB = "")
      )
    )
  })
}

shinyApp(ui,server)
```

**Comment by bellma-lilly** [comment]
@rdemets 
I'm not sure why this stays hidden, but the following fixed the issue for me:
 observeEvent(input$sidebarItemExpanded, { 
    runjs("$('#tree > ul').css('display', 'block');")
  })

**Comment by rdemets** [comment]
Your code works. 

I tried to modify this block based on your answer but its not working. But I guess it doesnt matter, 

```
js <- "
$(document).ready(function() {
    $('a[href=\"#shiny-tab-location\"').on('click', function() {
#        $('.treejs-nodes').css('display', 'block');
        $('#tree > ul').css('display', 'block');
    });

})
"
```

Thanks a lot
