### ISSUE TITLE
`which_selected` function

### ISSUE THREAD

**Issue by jangorecki** [shinyTree/shinyTree#13]
Hi,
I would like to fill FR for `which_selected` function to return indices of lists and nested lists. The best if it would return the integer vector of indices which can be used in a way `mylist[[indices]]` to access selected element in any list of the same structure.
I would prefer to have two lists, one the _labels list_ which is visible on the UI, other one the _data list_ (various data types including language objects) the mirror structure of _labels list_. Using `which_selected` on the _labels list_ I could easily access the element from the mirror _data list_.
Or maybe there is a simple trick to achieve it now?

**Comment by trestletech** [comment]
Hi, I'm not sure I understand the request. Can you provide an example and/or some code samples that describe the format of the data you have now and what you're looking for? Thanks.

**Comment by jangorecki** [comment]
Sure.
Consider following tree
```r
  output$tree <- renderTree({
    mylist <- list(
      root1 = structure("123"),
      root2 = list(
        SubListA = list(leaf1 = "", leaf2 = "", leaf3=""),
        SubListB = list(leafA = "", leafB = "")
      )
    )
  })
```
The `which_selected` function would return:
- nothing selected: `NA_integer_`
- selected `root1`: `1L`
- selected `root2-SubListA-leaf3`: `c(2L,1L,3L)`
- selected `root2-SubListB`: `c(2L,2L)`
- selected `root2-SubListB-leafA`: `c(2L,2L,1L)`

Having such integer vector output I could subset `mylist[[int_vec]]` or any other lists with exact structure.

In my use case I have a second *technical* lists of the same structure which contains `call`s and `symbol`s. Those will be execute on selection. Currently I've manage to do this using `get_selected` but I had to prefix list names with unique numbers to catch those numbers and reuse on subset *technical* list. So currently my shinyTree names are cluttered by unique id.

**Comment by schaffman5** [comment]
#21 closes this issue.
