### ISSUE TITLE
add updateTree

### ISSUE THREAD

**Issue by yannrichet** [shinyTree/shinyTree#14]
This could be necessary to not loose the reference to the input$tree object, for instance when calling a get_selected() in an observer.
Useful to display a list which is often updated.
Best regards,
Yann

**Comment by trestletech** [comment]
Sure. What sorts of features would you envision for this update function? Can you give an example or two of what arguments you might use with, for instance,

```
updateTree(session, "myTree", ...
```

**Comment by yannrichet** [comment]
Well, I think a first version should just include the tree list object: updateTree(session, "tree", newtree=list(...))
It might be useful to update just some leaf in the tree, but it is not easy to produce a clear API for that.

**Comment by schaffman5** [comment]
#21 closes this issue.
