### ISSUE TITLE
Node labels?

### ISSUE THREAD

**Issue by yindeng** [shinyTree/shinyTree#16]
I really like your package and been using it in my shiny app. I was wondering if it would be possible to provide labels for the tree nodes. Right now the labels are the same as the names of the nested lists, but it's often useful to have them be something else (like the selectInput in shiny, we can specify a named vector for the choices so the labels will be the names of the vector while the selected value is the corresponding value of the vector). In terms of implementation, I think the easiest way for users of shinyTree would be to add an optional attribute for each node like "stlabel". Is that doable? Thanks.

**Comment by schaffman5** [comment]
#21 closes this issue.

**Comment by nick-youngblut** [comment]
@schaffman5 is there documentation on adding node IDs? Can one use non-unique IDs?

**Comment by nick-youngblut** [comment]
Moreover, it seems that https://github.com/shinyTree/shinyTree/blob/master/inst/examples/10-node-ids/server.R relies on the fact that R allows for non-unique keys in lists if a list is declared fully:

```
  list(
    'Project A' =  list(
        'Study A-A'=structure('',stid=1,stclass='study'), 
        'Study A-A'=structure('',stid=2,stclass='study')
      ),
    'Project A' = list(
        'Study A-A'=structure('',stid=3,stclass='study'), 
        'Study A-A'=structure('',stid=4,stclass='study')
      )
  )
```

...versus creating a nested list iteratively:

```
L = list()
for (i in 1:length(children)){
   child = children[i]
   L[[child]] = structure('', stid=i, stclass='study')
}
```
