### ISSUE TITLE
get_selected frozen when a tree depends on inputs

### ISSUE THREAD

**Issue by LSanselme** [shinyTree/shinyTree#17]
Hello,
I am having issues with the selected node of the tree, when the tree depends on inputs.
Here is a minimal working example:

``` r
#ui.R
library(shiny)
library(shinyTree)

shinyUI(
  sidebarLayout(
    sidebarPanel(
      selectInput("idTree",
                  label = "Select a tree",
                  choices = list("A" = "A",
                                 "B" = "B"),
                  selected = "A")
    ),
    mainPanel(
      shinyTree("tree"),
      h4("currently selected:"),
      textOutput("idSelected")
    )
  )
)
```

``` r
#server.R
library(shiny)
library(shinyTree)

createTree<- function(idTree){
  switch(idTree,
         "A" =   list(A1 = list(A2 = "a", A3 = "b"), A4 = "c"),
         "B" =   list(B1 = list(B2 = "d"), B3 = "e", B4 = "f"))}

shinyServer(function(input, output) {

  getIdSelected <- reactive({
    tree <- input$tree
    unlist(get_selected(tree))
  })

  output$idSelected <- renderText({ 
    getIdSelected()
  })

  output$tree <- renderTree(
    {createTree(input$idTree)}
  )
})

```

At first, the selected node is displayed correctly, but as soon as the input `idTree` changes, the selection `idSelected` seems frozen, whereas `tree` is correctly updated.
I may be doing something wrong, but I can't see where after a couple hours of struggling. Am I missing something in the way shinyTree works?

**Comment by nick-ulle** [comment]
It appears that `input$tree` is never updated, even when the list supplied in `renderTree()` changes.

**Comment by nick-ulle** [comment]
After some investigation, I think the cause is line 11 in shinyTree.js, the call to `$elem.jstree('destroy');`. Updating the tree through jstree's API rather than destroying it and creating a new tree might fix the problem.

**Comment by sarvagna** [comment]
I'm facing the same problem. Was trying to figure what's wrong with my code. Can you suggest a fix please nick-ulle

**Comment by LSanselme** [comment]
Thanks for your investigation, nick-ulle! There is a workaround: refreshing the browser seems to force the tree to be in the updated state.

**Comment by oganm** [comment]
Refreshing the browser also refreshes the entire app and it's inconvenient to communicate to users. Are there any plans to fix this? An alternative might to have all possible trees rendered from the beginning and use shinyjs to hide/show trees but not really ideal.

**Comment by oganm** [comment]
As a potential workaround I tried to create a tree using htmlOutput but using that turns the tree into a list

**Comment by oganm** [comment]
I found a workaround using [shinyjs](https://github.com/daattali/shinyjs). You have to initiate the tree the way it looks on page load. Then you use a javascript function to modify the tree. The problem with this is that updated tree seems to ignore any state information provided through the json input. So If you opened the first node, the new tree will also have the first node open. Theoretically you should be able to tell it to select specific nodes but I didn't have time to deal with those. I just deselect everything and force every node to open. This obviously wont work on modifying node states without some tinkering but it's a start. In [this](https://gist.github.com/oganm/09662e6ff11384f5ce58) gist I modified @LSanselme's code to work properly. Hope the package supports updated trees as well.

**Comment by pan0ramic** [comment]
FWIW: +1 on this issue. I cannot use shinyTree without being able to dynamically update the tree and get the selection

**Comment by schaffman5** [comment]
#21 closes this issue.
