### ISSUE TITLE
updating input$tree with new values

### ISSUE THREAD

**Issue by joe-gz** [shinyTree/shinyTree#22]
I have an observeEvent set up on the input$tree like so:
`observeEvent(input$tree[1], {
      print('stop me')
    }, autoDestroy = FALSE)
    load("www/dir_tree.Rdata")
    output$tree <- renderTree(tree, quoted = FALSE)`

If i change the tree, in other words, select a new folder with a different set of files using `shinyDirButton`, that observeEvent essentially dies, because input$tree does not update. Is there anything I can do to refresh input$tree to the new correct values?

The actual display tree DOES update after I call renderTree, but the input that my observeEvent is watching does not.

**Comment by Hoeze** [comment]
I've got exactly the same problem.
As soon as I re-render my tree, all other plots depending on my selection do not update any more.

**Comment by wfw119** [comment]
Hello @joe-gz  and @Hoeze ,

I have got the same problem. I tried updateTree() but it didn't work. My tree is based on a mongodb collection. When the user saves new inputs to the db and clicks "update" button, the tree list is actually updated but the input$tree's not. More importantly, the input$tree is further used for tables, graphs, and maps. I'm wondering if you guys already solve the issue. Really want to share the problem and ideas with you.

**Comment by Hoeze** [comment]
I don't really understand your problem.

I was doing something like this:
```
shinyServer(function(input, output, session) {
     react = reactiveValues()
     react$patient_sel_list = [...]
     observe({
         updateTree(session, "tree", data=[...], selected_samples = react$patient_sel_list))
     })
```
This worked for me seamlessly. I could use input$tree as reactive input.

**Comment by schaffman5** [comment]
#21 closes this issue.
