### ISSUE TITLE
updateTree and page refresh causes error

### ISSUE THREAD

**Issue by YsoSirius** [shinyTree/shinyTree#47]
It is not clear how to use the `updateTree` method. Does it work only in combination with `renderEmptyTree` or can you pass an initial tree in `renderTree`, which can be updated in an `observe`/`observeEvent`?

Using an `observe` to dynamically update the tree, crashes the app on a page refresh and gives this error:

> Warning: Error in [[: subscript out of bounds
>   [No stack trace available]
> Error in json[[i]] : subscript out of bounds

The only way I achieved that is by using an `actionButton`+`observeEvent` for the update event. But this feels weird, to always press the button for a different sorting. Can this be prevented?

```
library(shiny)
library(shinyTree)

trl <-     list(
  root1 = list(leaf0 = ""),
  root2 = list(
    SubListA = list(leaf1 = list(
      leaf11 = "", leaf12 = ""),
      leaf2 = "", leaf3=list(
        leaf31 = "", leaf32 = ""
        )
      )),
  root3 = list(leafA = "", leafB = "")
  )
)

ui <- {fluidPage(
  selectInput("change", label = "Change Order", multiple = F, choices = c("", "Names-Rev", "Names"), selected = ""),
  actionButton("updateTree", "Update Tree"),
  shinyTree("tree", dragAndDrop = T, themeIcons = T,   themeDots =T)
)}

server <- function(input, output, session) {
  
  output$tree <- renderTree({
    trl
  })
  
  # observe({
  observeEvent(input$updateTree,{
    req(input$change != "")
    
    if (input$change == "Names-Rev") {
      newtree <- trl[rev(order(names(trl)))]
    } else if (input$change == "Names") {
      newtree <- trl[order(names(trl))]
    }
    updateTree(session, "tree", newtree)
  })
}

shinyApp(ui,server)

```

**Comment by bellma-lilly** [comment]
updateTree works without renderEmptyTree; see example 12-types (and your example, which works for me).  
Could you explain further what you mean by a page refresh? Are you using the browser reload button?
Can you provide an example that causes the error?

**Comment by trafficonese** [comment]
Yes, that example works with that actionButton. Uncommenting the `observeEvent` and replacing it with the normal `observe` will enable the error.

So, load the app, change the Order and refresh/reload the browser and that error will show up and break the app.

**Comment by bellma-lilly** [comment]
I can't reproduce this error. It works fine for me.  Refreshing the browser is not usually part of the workflow for a shiny app anyway.  Are you using IE? perhaps something is being cached.

**Comment by trafficonese** [comment]
No, Im using Firefox, but this error appears with Chrome and IE aswell.

Workflow to produce the error:
1. Start the app
2. Change the order (Choose "Names-Rev" or "Names")
3. Reload the page (hit F5)

Here is the example that produces the error:

```
library(shiny)
library(shinyTree)

trl <-     list(
  root1 = list(leaf0 = ""),
  root2 = list(
    SubListA = list(leaf1 = list(
      leaf11 = "", leaf12 = ""),
      leaf2 = "", leaf3=list(
        leaf31 = "", leaf32 = ""
      )
    )),
  root3 = list(leafA = "", leafB = "")
)
)

ui <- {fluidPage(
  selectInput("change", label = "Change Order", multiple = F, choices = c("", "Names-Rev", "Names"), selected = ""),
  shinyTree("tree", dragAndDrop = T, themeIcons = T,   themeDots =T)
)}

server <- function(input, output, session) {
  
  output$tree <- renderTree({
    trl
  })
  
  observe({
    req(input$change != "")
    if (input$change == "Names-Rev") {
      newtree <- trl[rev(order(names(trl)))]
    } else if (input$change == "Names") {
      newtree <- trl[order(names(trl))]
    }
    updateTree(session, "tree", newtree)
  })
}

shinyApp(ui,server)
```

I know that a browser refresh is not really part of a shiny-app, but it shouldnt break the app anyway or?

**Comment by trafficonese** [comment]
I removed the error (if you meant the extra bracket?) in the example.

I had the list already in memory, thats why I could still load the app. Anyway, that didnt have anything to do with the mentioned error. 

I think that after a refresh it tries to render the normal tree with renderTree and update the tree if the observe is triggered (which it will, when an ordering is selected). I am pretty sure, this is an `updateTree` or even `Rlist2json` problem. 

Even the error msg suggests that or?
`Error in json[[i]] : subscript out of bounds`

**Comment by YsoSirius** [comment]
This error doesnt happen anymore after the latest Firefox update
