### ISSUE TITLE
Dev-version (0.2.6) is broken.

### ISSUE THREAD

**Issue by trafficonese** [shinyTree/shinyTree#53]
Wit the latest dev-version, I am getting this error msg in the browser console:

`SyntaxError: expected expression, got '<<'`

In the shinyTree.js there are those lines of code:
```
<<<<<<< HEAD
=======
          callbackCounter++;
>>>>>>> upstream/master
```

which cause the problem apparently.

**Comment by bellma-lilly** [comment]
thanks; I merged the icons pull request to fix this
