### ISSUE TITLE
updateTree looses css-class

### ISSUE THREAD

**Issue by YsoSirius** [shinyTree/shinyTree#54]
By updating a tree, the `stclass` gets lost.

```
library(shiny)
# devtools::install_github("shinyTree/shinyTree")
library(shinyTree)

treedata =     list(
  root1 = structure("", stclass="red-node"),
  root2 = structure(list(
    SubListA = list(leaf1 = "", leaf2 = "")
  ), stclass="blue-node")
)

ui <- fluidPage(
  tags$head(tags$style("
                      .red-node {
                        color: #F00;
                      }
                      .blue-node {
                        color: #00F;
                      }")),
  actionButton("update", "Update Tree"),
  shinyTree("tree")
)

server <- function(input, output, session) {
  output$tree <- renderTree({
    treedata
  })
  
  observeEvent(input$update, {
    updateTree(session, "tree", treedata)
  })
}

shinyApp(ui, server)
```

**Comment by bellma-lilly** [comment]
Please use types to set styles:

```
library(shiny)
library(shinyTree)

treedata =     list(
  root1 = structure("", sttype="red-node"),
  root2 = structure(list(
    SubListA = list(leaf1 = "", leaf2 = "")
  ), sttype="blue-node")
)

ui <- fluidPage(
  actionButton("update", "Update Tree"),
  shinyTree("tree"
  ,types = "{
     'red-node': {'a_attr' : { 'style' : 'color:red' }},
     'blue-node': {'a_attr' : { 'style' : 'color:blue' }}
  }"
  )
)

server <- function(input, output, session) {
  output$tree <- renderTree({
    treedata
  })
  
  observeEvent(input$update, {
    updateTree(session, "tree", treedata)
  })
}

shinyApp(ui, server)
```
(I see that the blue node moves a little bit on the update. That needs to be fixed)

**Comment by trafficonese** [comment]
What if my type and color nodes are different?

I need the types for ordering (drag&drop), but the coloring logic is different. I tried setting multiple types but they get overwritten and only the last type is kept.

That is why I used the "stclass", but unfortunately that gets overwritten after a tree update. So I have to implement some additional JavaScript to color the nodes after the first update.

**Comment by bellma-lilly** [comment]
I'm not following you completely. There can be as many types as you want, but each node may only have one type currently.  Perhaps class functionality can be implemented at some point

**Comment by trafficonese** [comment]
Let's assume this is my tree:
-- A
   ----- A1
   ----- A2
   ----- A3
-- B
   ----- B1
   ----- B2
   ----- B3

The nodes A & B are of type root1, and the nodes A1,A2,A3 and B1,B2,B3 are all of type root2.
But I only need to color the nodes A2 and B2.
So these nodes would need 2 types (root2 and color).

And since I cannot have 2 types on 1 node, I used the class attribute with CSS to add some color.

I hope that clarifies my problem.

**Comment by bellma-lilly** [comment]
We're on the same page.  One option, that may or may not be useful, is to have types for all of the root1_color root2_color combinations.

**Comment by trafficonese** [comment]
That is indeed an option, I also thought about that. I will give it a try.

But just for future features: Would it be possible to retain the "stclass" after a tree update?

And thanks for your time!

**Comment by bellma-lilly** [comment]
I will add that as a feature request
