### ISSUE TITLE
Visualizing folder / file structure using shinyTree

### ISSUE THREAD

**Issue by akubisch** [shinyTree/shinyTree#55]
Hi! First of all this is a very nice package coming in handy for a requirement in a dashboard I'm working on. The idea is to represent the shiny server's file structure in order to manage dashboards lying there. Now I'm wondering what a good way could be to easily transfer the result of `list.files("./", recursive = TRUE)` to a nested structure that can be handled by shinyTree? I've written a function that gets me a nested list first of all without any discrimination between files and folders. This works for two hierarchical levels, but more than 2 leads to an app crash. I've seen that in some situations one needs to use `structure`, but I did not get, when to use what (see example below)!? Could you probably bring some light into the last point?

And is there probably already a method existing for displaying file structure? Since I guess that this will be a rather common use case...

Thanks a lot in advance!

The aforementioned example on the use of structures and lists (I see that structure allows for providing additional information, like stopened, but if I leave that out and turn it to a list it doesn't work):
```list(
  '1 level'= list( 
    '1.1 level' = structure(
      list('1.1.1 level'=
             list('1.1.1.1 level'=
                    list('1.1.1.1.1'='1')),
           '1.1.2 level'='2'),stopened=TRUE)
  ),
  '1.2 level' = structure(
    list('1.2.1 level' = '3'),stopened=TRUE)
)
```

**Comment by bellma-lilly** [comment]
We need the input to shinyTree to be a list of lists. files.list just returns a list.  Below is a full example of a directory structure that I will be committing to the repo soon. You will need to set the path to something appropriate and be careful with the maxdepth, as that can get out of hand, of course.

```
library(shiny)
library(shinyTree)

shinyServer(function(input, output, session) {
  listFiles <- function(maxDepth,path,currentDepth=1){
    dirs <- list.dirs(path,recursive = FALSE, full.names = FALSE)
    allFiles <- list.files(path,list.dirs(recursive = FALSE, full.names = FALSE))
    files <- setdiff(allFiles, dirs)
    if(length(dirs) != 0 && (maxDepth == 0 || currentDepth < maxDepth)){
      subtree <- append(lapply(dirs,
        function(nextDir){
          nextDir = structure(listFiles(maxDepth,file.path(path,nextDir),currentDepth+1),sttype="directory")
        }),files
      )
      names(subtree) <- append(dirs,files)
      subtree
    }else{
      subtree <- append(lapply(dirs,
        function(nextDir){
          structure(nextDir,sttype="directory")
        }),files
      )
      names(subtree) <- append(dirs,files)
      subtree
    }
  }
 
  treeStructure <- listFiles(3,"..")
  output$tree <- renderTree(treeStructure)
})
```
```
library(shiny)
library(shinyTree)

shinyUI(
  pageWithSidebar(
    # Application title
    headerPanel("Simple shinyTree!"),
    
    sidebarPanel(
      helpText(HTML("Directory Structure example"))
    ),
    mainPanel(
      # Show a simple table.
      shinyTree("tree",types= #Types is in the same format that jstree expects
        "{
          'directory' : { 'icon' : 'glyphicon glyphicon-folder-open' },
          'default' : { 'icon' : 'glyphicon glyphicon-file', 'valid_children' : [] }
         }"
      )
    )
  ))
```
