### ISSUE TITLE
stringr dependency / build failing

### ISSUE THREAD

**Issue by trafficonese** [shinyTree/shinyTree#59]
Currently there are 2 `fixIconName` functions in **update-tree.R**.

And there is also a call to load the `library(stringr)`, which should be added in the DESCRIPTION / NAMESPACE instead.

I could adapt that and add a PR for that, but I could also remove the `stringr` dependency and do the regexing with base-R.

**Comment by bellma-lilly** [comment]
Thanks, I have fixed these.

**Comment by trafficonese** [comment]
Almost :)

`library(stringr)` is still there.

**Comment by bellma-lilly** [comment]
You're right; I added it to the description, but didn't remove the library call. It's gone now
