### ISSUE TITLE
How to setup a root node?

### ISSUE THREAD

**Issue by SamGG** [shinyTree/shinyTree#60]
Hi,
Thanks for this very nice package. I did some tests with JsTree and then come to shinyTree.
Currently, I need a selectable root node, ie a node that is the unique parent of the root1 and root2 nodes found in your examples. How to achieve this?
Best.

**Comment by trafficonese** [comment]
Do you mean something like this tree?

There is a `unique` plugin for jsTree, but it is currently not implemented in shinyTree, although there's a PR that implements that.  #46 

Otherwise you have to check for uniqueness before rendering the tree.

```
library(shiny)
library(shinyTree)

dt <- list(
  root = list(
    root1 = structure("123",stinfo="A"),
    root2 = list(
      SubListA = list(leaf1 = structure("leaf1",stinfo="B"), leaf2 = "", leaf3=""),
      SubListB = list(leafA = "", leafB = "")
    )
  )
)

ui <- fluidPage(shinyTree("tree"))

server <- function(input, output, session) {
  output$tree <- renderTree({
    dt
  })
}

shinyApp(ui, server)
```

**Comment by SamGG** [comment]
Thanks for your help.
That sounds fine and answers my question.
Best.
