### ISSUE TITLE
Find/Add/Delete nodes

### ISSUE THREAD

**Issue by SamGG** [shinyTree/shinyTree#64]
Hi,
I want to interact with a tree, ie to add, delete node using R (because I am not fluent in Javascript). Are there functions to do that ?
Best.

**Comment by trafficonese** [comment]
You can find nodes with the `search` argument (either with `search=TRUE` or `search="inputID_of_textInput"`).

For adding/deleting/renaming nodes, there is the jsTree-plugin `contextmenu` which is included in #46.
But those changes are only temporary, unless you save the new/adapted tree and reload it then.

**Comment by SamGG** [comment]
Thanks for your reply. I will look at the contextmenu.
Best
