### ISSUE TITLE
Feature Request: contextmenu

### ISSUE THREAD

**Issue by obkhan** [shinyTree/shinyTree#71]
Hi, I saw a pull request that may have had contextmenu ? Would it be possible to enable it?
https://github.com/shinyTree/shinyTree/pull/46

**Comment by YsoSirius** [comment]
Yes, enabling the contextmenu was not the big deal, but it didn't work properly with the checkbox plugin.

And also, all changes (renaming/creating/deleting) made to the tree would only be temporary.
