### ISSUE TITLE
get_selected() does not change when tree is updated with updateTree()

### ISSUE THREAD

**Issue by m-merchant** [shinyTree/shinyTree#78]
This issue is in reference to a [question](https://stackoverflow.com/questions/56555281/r-shiny-updating-shinytree-node-selections/56556146?noredirect=1#comment99695083_56556146) I had posted on SE.

The app below contains a shinyTree, a reset button (`Reset nodes`) and a print output `Selected nodes`, which returns a list of selected nodes using `get_selected`. 

Here is a screenshot of the tree on start-up:

![image](https://user-images.githubusercontent.com/41273227/59579471-17c14080-9121-11e9-88f4-8771f8a96ebc.png)

No nodes are selected so `get_selected` returns an empty list().

When I make a selection, e.g. node `a`, `get_selected` correctly returns that selection:

![image](https://user-images.githubusercontent.com/41273227/59579511-3de6e080-9121-11e9-81cd-3863809d3913.png)

When I click `Reset nodes`, the node selections are cleared in the tree UI but the list returned by `get_selected` does not change to reflect this:

![image](https://user-images.githubusercontent.com/41273227/59579581-a635c200-9121-11e9-891f-101b1699199f.png)

**I would expect `get_selected` to return `list()` when I click `Reset nodes`.** 

Here is the reprex:

```
library(shiny)
library(shinyTree)

tree = list(a=list(a1=1,a2=2) , b="b") 

tree = lapply(tree, function(x) structure(x, stopened = T))

ui <- fluidPage(
  sidebarLayout(
    sidebarPanel(
      actionButton('reset', 'Reset nodes')
    ),
    mainPanel(
      shinyTree("tree", ),
      hr(),
      "Selected nodes:",
      verbatimTextOutput("idSelected")#,
    )
  )
)

# server

server <- function(input, output, session) {
  
  output$tree = renderTree({
    
    tree
    
  })
  
  
  output$idSelected <- renderPrint({
    str(get_selected(input$tree, format = "classid"))
  })
  
  
  # An observer is used to trigger a tree update when reset is clicked.
  observeEvent(input$reset, {
    
    updateTree(session,"tree", data = tree)
    
    print(get_selected(input$tree, format = "classid"))
  })
}

shinyApp(ui, server)
```

I was wondering if this feature was intended or if I was modelling the tree incorrectly?

**Comment by bellma-lilly** [comment]
People generally don't want a callback when update tree is called because they already know what is in the tree. Certainly, input$tree would not be updated immediately after updateTree was called; you would still need to get the new input$tree in an observe. The answer by @ismirsehregal (on stackexchange) is an elegant solution to your particular problem

**Comment by bellma-lilly** [comment]
@trafficonese Can you explain your pull request so we can understand how you intend it to be used to solve the problem?

**Comment by Merchant93** [comment]
Thanks for following up on this @bellma-lilly. I am still not sure why the disconnect between `updateTree` and `get_selected` exists but can appreciate that it was an intended feature. 

Could you please clarify what you mean by 'you would still need to get the new input$tree in an observe'?

**Comment by trafficonese** [comment]
By including `set_state.jstree` or `refresh.jstree` the mentioned problem gets fixed and I think it also makes more sense because it corresponds to the visual representation of the tree.

**Comment by bellma-lilly** [comment]
@Merchant93 updateTree sends a message to the browser to change the tree, but input$tree, which is part of R and not in the browser is not yet changed.  Your observeEvent, which calls updateTree, will exit with  input$tree unchanged.

At some point later, the tree in the browser could alert the R server that the tree has changed and input$tree needs to be updated.  You would need an observe to detect when input$tree has been updated.

**Comment by bellma-lilly** [comment]
@trafficonese 
I am concerned that using set_state will cause unintended problems for existing code. I will include it if it is turned on as a option that is false by default.

**Comment by Merchant93** [comment]
Thank you for clearing that up @bellma-lilly. I think the confusion came from me expecting `updateTree` to work like `updateSelectInput(session, inputId = 'month', selected = month.abb[2])` where specifying the `selected` argument changes `input$month` to `month.abb[2]`.

**Comment by bellma-lilly** [comment]
@Merchant93 Maybe it should work like that. I'll keep that in mind.
