### ISSUE TITLE
Feature Request: Integrate parser from/to data.tree

### ISSUE THREAD

**Issue by thothal** [shinyTree/shinyTree#88]
`library(data.tree)` seems to be a natural companion to `shinyTree` as it is a data structure tailor made to trees. Ideally we could pass the list representation from `data.tree` to `shinyTree` and vice versa.

It turns out that the data structures are very similar except that where `shinyTree` uses attributes, `data.tree` uses list slots. 

I wrote two very small parser functions, to move easily from one format to another. This parsers are far from being perfect, but I wanted to provide these functions for discussions nevertheless.

You can find the source in [this Gist.](https://gist.github.com/thothal/898e2fdbe23867b16ff477c82ab8cc56)

If this of interest I could create a PR, but would like to hear your feedback first?

```R
shiny::runGist("https://gist.github.com/thothal/898e2fdbe23867b16ff477c82ab8cc56")
```

**Comment by trafficonese** [comment]
I think that would be very useful.

There is already #30, which allows to pass `data.tree` objects to `renderTree`, but it might be a bit outdated. 

From my POV you could definitly add a PR with those functions, as a conversion back and forth would be very useful and may help users transform a `data.frame` more easily to a `shinyTree` compatible list.

Can you also include your gist as an example? And maybe another example where you transform a data.frame to a shinyTree?

**Comment by thothal** [comment]
Thanks for the feedback  @trafficonese. Will add a PR. Since I am quite a novice user to GitHUB collaboration, what is the best practice? Should I fork from the main repo, or from your PR?

**Comment by trafficonese** [comment]
I would recommend opening a new PR.

So fork the main repo, include the new functions with a new example in `/inst/examples`, add the example in the README, add a short description of the new functionality in NEWS, push everything to your fork and open a PR with it.

**Comment by thothal** [comment]
I mean the easiest would be to change the `inputHandler` to something like this:

```R
registerInputHandler("shinyTree", function(val, shinysession, name){
     val$callbackCounter <- NULL # set to null as of no interest
    data.tree::as.Node(list(children = val),
                           "explicit",
                       nameName = "text")
  }
```

In this way you would get back a `data.tree` automatically, but this would break a lot of code and is not backwards compatible.  The solution highlighted in my gist works, butI feel it is a bit of overkill to first loop through the JSON in the existing `inputHandler` and then to loop through this return value again to transform it into yet another format. 

But since this solution would keep backwards  compatibility I will go for the solution in the gist. Any thoughts on that?
