### ISSUE TITLE
checkbox but only allow user to select one folder?

### ISSUE THREAD

**Issue by MayaGans** [shinyTree/shinyTree#96]
Just curious - is it possible to limit the user to only selecting a single file in the tree? Thank you again for this wonderful package!!

**Comment by trafficonese** [comment]
What if you set `multiple` to `FALSE`? Or do you use checkboxes?

Is example 1 what you're after?
```
library(shiny)
runApp(system.file("examples/01-simple", package = "shinyTree"))
```

**Comment by MayaGans** [comment]
Duh! Sorry! That's perfect thanks!
